/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as NewUsersRouteImport } from './routes/new-users'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'

const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUsersRoute = NewUsersRouteImport.update({
  id: '/new-users',
  path: '/new-users',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/broadcast': typeof BroadcastRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/hello': typeof HelloRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/new-users': typeof NewUsersRoute
  '/pipeline': typeof PipelineRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/broadcast': typeof BroadcastRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/hello': typeof HelloRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/new-users': typeof NewUsersRoute
  '/pipeline': typeof PipelineRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/broadcast': typeof BroadcastRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/hello': typeof HelloRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/new-users': typeof NewUsersRoute
  '/pipeline': typeof PipelineRoute
  '/register': typeof RegisterRoute
  '/seller': typeof SellerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/broadcast'
    | '/contact'
    | '/contacts'
    | '/hello'
    | '/import'
    | '/inventory'
    | '/login'
    | '/matches'
    | '/new-users'
    | '/pipeline'
    | '/register'
    | '/seller'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/broadcast'
    | '/contact'
    | '/contacts'
    | '/hello'
    | '/import'
    | '/inventory'
    | '/login'
    | '/matches'
    | '/new-users'
    | '/pipeline'
    | '/register'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/broadcast'
    | '/contact'
    | '/contacts'
    | '/hello'
    | '/import'
    | '/inventory'
    | '/login'
    | '/matches'
    | '/new-users'
    | '/pipeline'
    | '/register'
    | '/seller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BroadcastRoute: typeof BroadcastRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  HelloRoute: typeof HelloRoute
  ImportRoute: typeof ImportRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  NewUsersRoute: typeof NewUsersRoute
  PipelineRoute: typeof PipelineRoute
  RegisterRoute: typeof RegisterRoute
  SellerRoute: typeof SellerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-users': {
      id: '/new-users'
      path: '/new-users'
      fullPath: '/new-users'
      preLoaderRoute: typeof NewUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BroadcastRoute: BroadcastRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  HelloRoute: HelloRoute,
  ImportRoute: ImportRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  NewUsersRoute: NewUsersRoute,
  PipelineRoute: PipelineRoute,
  RegisterRoute: RegisterRoute,
  SellerRoute: SellerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
